// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: maxcpu.proto

package maxcpu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MaxCPU_GetStats_FullMethodName = "/maxcpu.MaxCPU/GetStats"
	MaxCPU_Hello_FullMethodName    = "/maxcpu.MaxCPU/Hello"
)

// MaxCPUClient is the client API for MaxCPU service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaxCPUClient interface {
	GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatsResponse, error)
	Hello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloResponse, error)
}

type maxCPUClient struct {
	cc grpc.ClientConnInterface
}

func NewMaxCPUClient(cc grpc.ClientConnInterface) MaxCPUClient {
	return &maxCPUClient{cc}
}

func (c *maxCPUClient) GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, MaxCPU_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maxCPUClient) Hello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, MaxCPU_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaxCPUServer is the server API for MaxCPU service.
// All implementations must embed UnimplementedMaxCPUServer
// for forward compatibility.
type MaxCPUServer interface {
	GetStats(context.Context, *emptypb.Empty) (*StatsResponse, error)
	Hello(context.Context, *emptypb.Empty) (*HelloResponse, error)
	mustEmbedUnimplementedMaxCPUServer()
}

// UnimplementedMaxCPUServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaxCPUServer struct{}

func (UnimplementedMaxCPUServer) GetStats(context.Context, *emptypb.Empty) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedMaxCPUServer) Hello(context.Context, *emptypb.Empty) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedMaxCPUServer) mustEmbedUnimplementedMaxCPUServer() {}
func (UnimplementedMaxCPUServer) testEmbeddedByValue()                {}

// UnsafeMaxCPUServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaxCPUServer will
// result in compilation errors.
type UnsafeMaxCPUServer interface {
	mustEmbedUnimplementedMaxCPUServer()
}

func RegisterMaxCPUServer(s grpc.ServiceRegistrar, srv MaxCPUServer) {
	// If the following call pancis, it indicates UnimplementedMaxCPUServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MaxCPU_ServiceDesc, srv)
}

func _MaxCPU_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaxCPUServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaxCPU_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaxCPUServer).GetStats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaxCPU_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaxCPUServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaxCPU_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaxCPUServer).Hello(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MaxCPU_ServiceDesc is the grpc.ServiceDesc for MaxCPU service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaxCPU_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maxcpu.MaxCPU",
	HandlerType: (*MaxCPUServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _MaxCPU_GetStats_Handler,
		},
		{
			MethodName: "Hello",
			Handler:    _MaxCPU_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "maxcpu.proto",
}
