// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: maxcpu.proto

package maxcpu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_maxcpu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maxcpu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_maxcpu_proto_rawDescGZIP(), []int{0}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=Metrics,proto3" json:"Metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_maxcpu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maxcpu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_maxcpu_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Metric        float64                `protobuf:"fixed64,2,opt,name=Metric,proto3" json:"Metric,omitempty"`
	Epoch         int64                  `protobuf:"varint,3,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_maxcpu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_maxcpu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_maxcpu_proto_rawDescGZIP(), []int{2}
}

func (x *Metric) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metric) GetMetric() float64 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *Metric) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_maxcpu_proto protoreflect.FileDescriptor

const file_maxcpu_proto_rawDesc = "" +
	"\n" +
	"\fmaxcpu.proto\x12\x06maxcpu\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\"9\n" +
	"\rStatsResponse\x12(\n" +
	"\aMetrics\x18\x01 \x03(\v2\x0e.maxcpu.MetricR\aMetrics\"H\n" +
	"\x06Metric\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x16\n" +
	"\x06Metric\x18\x02 \x01(\x01R\x06Metric\x12\x14\n" +
	"\x05Epoch\x18\x03 \x01(\x03R\x05Epoch2\x7f\n" +
	"\x06MaxCPU\x12;\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x15.maxcpu.StatsResponse\"\x00\x128\n" +
	"\x05Hello\x12\x16.google.protobuf.Empty\x1a\x15.maxcpu.HelloResponse\"\x00B3Z1github.com/kazeburo/mackerel-plugin-maxcpu/maxcpub\x06proto3"

var (
	file_maxcpu_proto_rawDescOnce sync.Once
	file_maxcpu_proto_rawDescData []byte
)

func file_maxcpu_proto_rawDescGZIP() []byte {
	file_maxcpu_proto_rawDescOnce.Do(func() {
		file_maxcpu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maxcpu_proto_rawDesc), len(file_maxcpu_proto_rawDesc)))
	})
	return file_maxcpu_proto_rawDescData
}

var file_maxcpu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_maxcpu_proto_goTypes = []any{
	(*HelloResponse)(nil), // 0: maxcpu.HelloResponse
	(*StatsResponse)(nil), // 1: maxcpu.StatsResponse
	(*Metric)(nil),        // 2: maxcpu.Metric
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_maxcpu_proto_depIdxs = []int32{
	2, // 0: maxcpu.StatsResponse.Metrics:type_name -> maxcpu.Metric
	3, // 1: maxcpu.MaxCPU.GetStats:input_type -> google.protobuf.Empty
	3, // 2: maxcpu.MaxCPU.Hello:input_type -> google.protobuf.Empty
	1, // 3: maxcpu.MaxCPU.GetStats:output_type -> maxcpu.StatsResponse
	0, // 4: maxcpu.MaxCPU.Hello:output_type -> maxcpu.HelloResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_maxcpu_proto_init() }
func file_maxcpu_proto_init() {
	if File_maxcpu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maxcpu_proto_rawDesc), len(file_maxcpu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maxcpu_proto_goTypes,
		DependencyIndexes: file_maxcpu_proto_depIdxs,
		MessageInfos:      file_maxcpu_proto_msgTypes,
	}.Build()
	File_maxcpu_proto = out.File
	file_maxcpu_proto_goTypes = nil
	file_maxcpu_proto_depIdxs = nil
}
